registry_secret: ENC[AES256_GCM,data:b+s/0k26BjOs62QcHtTBAdggZUAYHdQjIH/xIezbmAEHxUd9ex7VgMFvlEFoLHf3F9lKzciyMN44CGqRtqqIN45JVJcOFpV+809S9Bx/HvpAtqX9hkSboZeHQYbGQjXcPOnzppjez2q9jpFnJLHiikNiPH+ks9+1wgBzt22I8xaz9a/CDea3NT9WcvUQOB0EMGoXXjw6K2aLL2zIm8i5WqNSsLsRTC31hvVNtacrsD/6lQ+2CZQHAwHJXX7xvIZFcrJbriEBXkUuHoRO3JdUOHqk4ElWWFYqeUMpqDMQeziss/ib5B7OcIIXfMFipHsfUmbh3cLlUnAYi0LlCVR6Txx4BGJ7hL6G8/yLZ2IbHVk5BNY3K+0WMgMnRtyChpOHdKTmqJYGPg8sRWDV+PPwmwarkYNvzMij+kbxzclAgP0Rx1S+a6BiA6JtQdxr,iv:icJPUD4n0/hqY+6088BM//gppcW4wPYXnDdrrU9YZsU=,tag:BmgvQhwkSgrHDqCU1/hcfw==,type:str]
secrets:
    sorry-cypress-secrets:
        aws_access_key_id: ENC[AES256_GCM,data:CWcTKEi94j98yEp7xLSDtumNw74=,iv:85YzeYyBnv7Su2bV+OOB6aK1Yo1ozoGPP5xz/EBf+Tg=,tag:3XHUdV8KLoykuDBEJ9ov4w==,type:str]
        aws_secret_access_key: ENC[AES256_GCM,data:hcAO8W0iTArvGXvPEmSNeeIaUBSF/1zky3vsy2lHHUYpDLTfq7TrQQ==,iv:+rDvcvbZGOqhzu5Bv3JztqUtUD1iEsegWNR0doOMVmQ=,tag:2CyU+qm5KLGkpxk30Zo7og==,type:str]
        prometheus_bearer: ENC[AES256_GCM,data:y7SJLq4aqVLqwGyVuaYXR8ytuHf0Yhu61JNCJvQ03i91PLD9pFnIaQ==,iv:1ZWOzcGB7aA8ZReBCY/G1k/SgnnUlWw6OQFkro6FITc=,tag:9Z5o6yQ0CeZ3YyRUMvbCQw==,type:str]
sops:
    kms:
    -   arn: arn:aws:kms:eu-west-1:096108736502:key/a94a1de9-5070-4e41-bcb1-caf4a2d823f5
        created_at: '2020-09-17T12:52:50Z'
        enc: AQICAHj1lC4IXMS9NZVoevrJoxgzoshzcvx2v4D8Y93+0hYHNAHNKsJQSBOqiGSrV/EDHSW1AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMjr3qeyPoX55nJ2ywAgEQgDtNbDWqrycjPiU/0/CvHyTqvCeaHUmUE6lwMktOlpLD1s0AQ/pwRNe6s6ZA7ei4Zj+htz/Co6+ICOWd/A==
        aws_profile: ""
    -   arn: arn:aws:kms:eu-west-3:096108736502:key/203af757-eb6e-48b1-9a98-9dfeb66ebc87
        created_at: '2020-09-17T12:52:50Z'
        enc: AQICAHjS/p2PTB17EELEeUZXROm6BkksZqBgJxnapJB5EYChiQFH7NCbQqpzBvPL45DhBqWhAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMu2PUEovL3S5zwyElAgEQgDsEXQYdp6M8Ll6orISX210V0cKpoylUqWQ11aXVfnnxIo81CrvuUfC289XQTY4gFBN/iZMo5RqtyWRzHQ==
        aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-02-09T17:20:44Z'
    mac: ENC[AES256_GCM,data:ZnsLkyku7Hb4XtSKDIO6T0R+TSl4lDVkT+LBisSibpbqNG3tYunuhyEEZ1M1+uryA2QeCBkj4SVHGcqlCNmMy4EsR1kK9en4RIBZkIOFv5syqcHnzX1BNVLJGf7qyHV9BYYrrjYIsIQUn36RUH75AalM3jM4MZI65jyGnVpY3x8=,iv:Bv0bOTyMNJTboXfwo7dK4inri44hG52fQW1RSrQCUWc=,tag:7Zqeb3gY42y7TMfeBn2AEw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.6.1
