{{- if .Values.api.enabled -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sorrycypress.fullname" . }}-api
  labels:
    component: api
  {{- include "sorrycypress.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      {{- include "sorrycypress.selectorLabels" . | nindent 6 }}
      component: api
  template:
    metadata:
      labels:
        {{- include "sorrycypress.selectorLabels" . | nindent 8 }}
        component: api
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "sorrycypress.serviceAccountName" . }}
      securityContext:
      {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.api.image.repository }}:{{ tpl .Values.api.image.tag . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MONGODB_DATABASE
              value: sorry-cypress
            - name: MONGODB_URI
              value: "mongodb://{{ include "sorrycypress.fullname" . }}-mongo:{{ .Values.mongo.service.port }}"
          ports:
            - name: {{ .Values.api.service.name }}
              containerPort: {{ .Values.api.service.port }}
              protocol: {{ .Values.api.service.protocol }}
          livenessProbe:
            httpGet:
              path: /health-check-mongo
              port: {{ .Values.api.service.port }}
          readinessProbe:
            httpGet:
              path: /health-check-mongo
              port: {{ .Values.api.service.port }}
          resources:
      {{- toYaml .Values.api.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
  {{- toYaml . | nindent 8 }}
  {{- end }}
  {{- end -}}