{{- if .Values.registry }}
apiVersion: v1
kind: Secret
metadata:
  name: registry-secret
  namespace: {{ .Release.namespace }}
  annotations:
    vault.security.banzaicloud.io/vault-role: default
type: kubernetes.io/dockerconfigjson
data:
  {{- with .Values.registry }}
  .dockerconfigjson: {{ printf "%s:%s" .username .password | b64enc | printf `{"auths":{"padoa.azurecr.io":{"username":"%s","password":"%s","auth":"%s"}}}` .username .password | b64enc }}
  {{- end }}
{{- end }} 