{{- if .Values.secrets }}
{{- range $key, $content := .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $key }}
data:
{{- range $secretKey, $secretContent := $content }}
  {{ $secretKey }}: {{ $secretContent | b64enc | quote }}
{{- end }}
{{- end }}
{{- end }}
